
var Module = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  return (
function(Module) {
  Module = Module || {};

var c;c||(c=typeof Module !== 'undefined' ? Module : {});var n={},p;for(p in c)c.hasOwnProperty(p)&&(n[p]=c[p]);c.arguments=[];c.thisProgram="./this.program";c.quit=function(a,b){throw b;};c.preRun=[];c.postRun=[];var q=!1,t=!1,u=!1,aa=!1;q="object"===typeof window;t="function"===typeof importScripts;u="object"===typeof process&&"function"===typeof require&&!q&&!t;aa=!q&&!u&&!t;var v="";function w(a){return c.locateFile?c.locateFile(a,v):v+a}
if(u){v=__dirname+"/";var x,ba;c.read=function(a,b){x||(x=require("fs"));ba||(ba=require("path"));a=ba.normalize(a);a=x.readFileSync(a);return b?a:a.toString()};c.readBinary=function(a){a=c.read(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&(c.thisProgram=process.argv[1].replace(/\\/g,"/"));c.arguments=process.argv.slice(2);process.on("uncaughtException",function(a){throw a;});process.on("unhandledRejection",y);c.quit=function(a){process.exit(a)};c.inspect=
function(){return"[Emscripten Module object]"}}else if(aa)"undefined"!=typeof read&&(c.read=function(a){return read(a)}),c.readBinary=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?c.arguments=scriptArgs:"undefined"!=typeof arguments&&(c.arguments=arguments),"function"===typeof quit&&(c.quit=function(a){quit(a)});else if(q||t)t?v=self.location.href:document.currentScript&&(v=
document.currentScript.src),_scriptDir&&(v=_scriptDir),0!==v.indexOf("blob:")?v=v.substr(0,v.lastIndexOf("/")+1):v="",c.read=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},t&&(c.readBinary=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),c.readAsync=function(a,b,d){var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=function(){200==e.status||
0==e.status&&e.response?b(e.response):d()};e.onerror=d;e.send(null)},c.setWindowTitle=function(a){document.title=a};var ca=c.print||("undefined"!==typeof console?console.log.bind(console):"undefined"!==typeof print?print:null),z=c.printErr||("undefined"!==typeof printErr?printErr:"undefined"!==typeof console&&console.warn.bind(console)||ca);for(p in n)n.hasOwnProperty(p)&&(c[p]=n[p]);n=void 0;function da(a){var b;b||(b=16);return Math.ceil(a/b)*b}
var ea={"f64-rem":function(a,b){return a%b},"debugger":function(){debugger}},fa=!1;function assert(a,b){a||y("Assertion failed: "+b)}var ha="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function ia(a){for(var b=A,d=a;b[d];)++d;if(16<d-a&&b.subarray&&ha)return ha.decode(b.subarray(a,d));for(d="";;){var e=b[a++];if(!e)return d;if(e&128){var f=b[a++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var g=b[a++]&63;if(224==(e&240))e=(e&15)<<12|f<<6|g;else{var h=b[a++]&63;if(240==(e&248))e=(e&7)<<18|f<<12|g<<6|h;else{var k=b[a++]&63;if(248==(e&252))e=(e&3)<<24|f<<18|g<<12|h<<6|k;else{var r=b[a++]&63;e=(e&1)<<30|f<<24|g<<18|h<<12|k<<6|r}}}65536>e?d+=String.fromCharCode(e):(e-=
65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}}
function ja(a,b,d){var e=A;if(0<d){d=b+d-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var h=a.charCodeAt(++f);g=65536+((g&1023)<<10)|h&1023}if(127>=g){if(b>=d)break;e[b++]=g}else{if(2047>=g){if(b+1>=d)break;e[b++]=192|g>>6}else{if(65535>=g){if(b+2>=d)break;e[b++]=224|g>>12}else{if(2097151>=g){if(b+3>=d)break;e[b++]=240|g>>18}else{if(67108863>=g){if(b+4>=d)break;e[b++]=248|g>>24}else{if(b+5>=d)break;e[b++]=252|g>>30;e[b++]=128|g>>24&63}e[b++]=128|g>>18&63}e[b++]=128|g>>
12&63}e[b++]=128|g>>6&63}e[b++]=128|g&63}}e[b]=0}}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");function ka(a,b){0<a%b&&(a+=b-a%b);return a}var buffer,C,A,la,ma,D,E,oa,pa;function qa(){c.HEAP8=C=new Int8Array(buffer);c.HEAP16=la=new Int16Array(buffer);c.HEAP32=D=new Int32Array(buffer);c.HEAPU8=A=new Uint8Array(buffer);c.HEAPU16=ma=new Uint16Array(buffer);c.HEAPU32=E=new Uint32Array(buffer);c.HEAPF32=oa=new Float32Array(buffer);c.HEAPF64=pa=new Float64Array(buffer)}
var F,G,ra,sa,ta,ua,I;F=G=ra=sa=ta=ua=I=0;c.reallocBuffer||(c.reallocBuffer=function(a){try{var b=C;var d=new ArrayBuffer(a);(new Int8Array(d)).set(b)}catch(e){return!1}return va(d)?d:!1});var wa;try{wa=Function.prototype.call.bind(Object.getOwnPropertyDescriptor(ArrayBuffer.prototype,"byteLength").get),wa(new ArrayBuffer(4))}catch(a){wa=function(b){return b.byteLength}}var xa=c.TOTAL_STACK||5242880,J=c.TOTAL_MEMORY||16777216;
J<xa&&z("TOTAL_MEMORY should be larger than TOTAL_STACK, was "+J+"! (TOTAL_STACK="+xa+")");c.buffer?buffer=c.buffer:("object"===typeof WebAssembly&&"function"===typeof WebAssembly.Memory?(c.wasmMemory=new WebAssembly.Memory({initial:J/65536}),buffer=c.wasmMemory.buffer):buffer=new ArrayBuffer(J),c.buffer=buffer);qa();
function K(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var d=b.G;"number"===typeof d?void 0===b.F?c.dynCall_v(d):c.dynCall_vi(d,b.F):d(void 0===b.F?null:b.F)}}}var ya=[],za=[],Aa=[],Ba=[],Ca=!1;function Da(){var a=c.preRun.shift();ya.unshift(a)}var M=0,Ea=null,N=null;c.preloadedImages={};c.preloadedAudios={};function O(a){return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}
(function(){function a(){try{if(c.wasmBinary)return new Uint8Array(c.wasmBinary);if(c.readBinary)return c.readBinary(f);throw"both async and sync fetching of the wasm failed";}catch(B){y(B)}}function b(){return c.wasmBinary||!q&&!t||"function"!==typeof fetch?new Promise(function(b){b(a())}):fetch(f,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+f+"'";return a.arrayBuffer()}).catch(function(){return a()})}function d(a){function d(a){k=a.exports;if(k.memory){a=
k.memory;var b=c.buffer;a.byteLength<b.byteLength&&z("the new buffer in mergeMemory is smaller than the previous one. in native wasm, we should grow memory here");b=new Int8Array(b);(new Int8Array(a)).set(b);c.buffer=buffer=a;qa()}c.asm=k;c.usingWasm=!0;M--;c.monitorRunDependencies&&c.monitorRunDependencies(M);0==M&&(null!==Ea&&(clearInterval(Ea),Ea=null),N&&(a=N,N=null,a()))}function e(a){d(a.instance)}function g(a){b().then(function(a){return WebAssembly.instantiate(a,h)}).then(a,function(a){z("failed to asynchronously prepare wasm: "+
a);y(a)})}if("object"!==typeof WebAssembly)return z("no native wasm support detected"),!1;if(!(c.wasmMemory instanceof WebAssembly.Memory))return z("no native wasm Memory in use"),!1;a.memory=c.wasmMemory;h.global={NaN:NaN,Infinity:Infinity};h["global.Math"]=Math;h.env=a;M++;c.monitorRunDependencies&&c.monitorRunDependencies(M);if(c.instantiateWasm)try{return c.instantiateWasm(h,d)}catch(l){return z("Module.instantiateWasm callback failed with error: "+l),!1}c.wasmBinary||"function"!==typeof WebAssembly.instantiateStreaming||
O(f)||"function"!==typeof fetch?g(e):WebAssembly.instantiateStreaming(fetch(f,{credentials:"same-origin"}),h).then(e,function(a){z("wasm streaming compile failed: "+a);z("falling back to ArrayBuffer instantiation");g(e)});return{}}var e="bind.wast",f="bind.wasm",g="bind.temp.asm.js";O(e)||(e=w(e));O(f)||(f=w(f));O(g)||(g=w(g));var h={global:null,env:null,asm2wasm:ea,parent:c},k=null;c.asmPreload=c.asm;var r=c.reallocBuffer;c.reallocBuffer=function(a){if("asmjs"===m)var b=r(a);else a:{a=ka(a,c.usingWasm?
65536:16777216);var d=c.buffer.byteLength;if(c.usingWasm)try{b=-1!==c.wasmMemory.grow((a-d)/65536)?c.buffer=c.wasmMemory.buffer:null;break a}catch(P){b=null;break a}b=void 0}return b};var m="";c.asm=function(a,b){if(!b.table){a=c.wasmTableSize;void 0===a&&(a=1024);var e=c.wasmMaxTableSize;b.table="object"===typeof WebAssembly&&"function"===typeof WebAssembly.Table?void 0!==e?new WebAssembly.Table({initial:a,maximum:e,element:"anyfunc"}):new WebAssembly.Table({initial:a,element:"anyfunc"}):Array(a);
c.wasmTable=b.table}b.__memory_base||(b.__memory_base=c.STATIC_BASE);b.__table_base||(b.__table_base=0);b=d(b);assert(b,"no binaryen method succeeded.");return b}})();F=1024;G=F+3712;za.push({G:function(){Fa()}},{G:function(){Ga()}});c.STATIC_BASE=F;c.STATIC_BUMP=3712;G+=16;function Ia(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var Ja=void 0;function Q(a){for(var b="";A[a];)b+=Ja[A[a++]];return b}
var R={},S={},T={};function Ka(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}function La(a,b){a=Ka(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}
function Ma(a){var b=Error,d=La(a,function(b){this.name=a;this.message=b;b=Error(b).stack;void 0!==b&&(this.stack=this.toString()+"\n"+b.replace(/^Error(:[^\n]*)?\n/,""))});d.prototype=Object.create(b.prototype);d.prototype.constructor=d;d.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return d}var Na=void 0;function V(a){throw new Na(a);}var Pa=void 0;
function Qa(a,b){var d=[];function e(a){a=b(a);if(a.length!==d.length)throw new Pa("Mismatched type converter count");for(var e=0;e<d.length;++e)W(d[e],a[e])}d.forEach(function(b){T[b]=a});var f=Array(a.length),g=[],h=0;a.forEach(function(a,b){S.hasOwnProperty(a)?f[b]=S[a]:(g.push(a),R.hasOwnProperty(a)||(R[a]=[]),R[a].push(function(){f[b]=S[a];++h;h===g.length&&e(f)}))});0===g.length&&e(f)}
function W(a,b,d){d=d||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var e=b.name;a||V('type "'+e+'" must have a positive integer typeid pointer');if(S.hasOwnProperty(a)){if(d.K)return;V("Cannot register type '"+e+"' twice")}S[a]=b;delete T[a];R.hasOwnProperty(a)&&(b=R[a],delete R[a],b.forEach(function(a){a()}))}var Ra=[],X=[{},{value:void 0},{value:null},{value:!0},{value:!1}];
function Sa(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=Ra.length?Ra.pop():X.length;X[b]={L:1,value:a};return b}}function Ta(a){return this.fromWireType(E[a>>2])}function Ua(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}
function Va(a,b){switch(b){case 2:return function(a){return this.fromWireType(oa[a>>2])};case 3:return function(a){return this.fromWireType(pa[a>>3])};default:throw new TypeError("Unknown float type: "+a);}}function Wa(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var d=La(b.name||"unknownFunctionName",function(){});d.prototype=b.prototype;d=new d;a=b.apply(d,a);return a instanceof Object?a:d}
function Xa(a){for(;a.length;){var b=a.pop();a.pop()(b)}}function Ya(a,b){var d=c;if(void 0===d[a].C){var e=d[a];d[a]=function(){d[a].C.hasOwnProperty(arguments.length)||V("Function '"+b+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+d[a].C+")!");return d[a].C[arguments.length].apply(this,arguments)};d[a].C=[];d[a].C[e.H]=e}}
function Za(a,b,d){c.hasOwnProperty(a)?((void 0===d||void 0!==c[a].C&&void 0!==c[a].C[d])&&V("Cannot register public name '"+a+"' twice"),Ya(a,a),c.hasOwnProperty(d)&&V("Cannot register multiple overloads of a function with the same number of arguments ("+d+")!"),c[a].C[d]=b):(c[a]=b,void 0!==d&&(c[a].N=d))}function $a(a,b){for(var d=[],e=0;e<a;e++)d.push(D[(b>>2)+e]);return d}
function ab(a,b){a=Q(a);if(void 0!==c["FUNCTION_TABLE_"+a])var d=c["FUNCTION_TABLE_"+a][b];else if("undefined"!==typeof FUNCTION_TABLE)d=FUNCTION_TABLE[b];else{d=c["dynCall_"+a];void 0===d&&(d=c["dynCall_"+a.replace(/f/g,"d")],void 0===d&&V("No dynCall invoker for signature: "+a));for(var e=[],f=1;f<a.length;++f)e.push("a"+f);f="return function "+("dynCall_"+a+"_"+b)+"("+e.join(", ")+") {\n";f+="    return dynCall(rawFunction"+(e.length?", ":"")+e.join(", ")+");\n";d=(new Function("dynCall","rawFunction",
f+"};\n"))(d,b)}"function"!==typeof d&&V("unknown function pointer with signature "+a+": "+b);return d}var bb=void 0;function cb(a){a=db(a);var b=Q(a);Y(a);return b}function eb(a,b){function d(a){f[a]||S[a]||(T[a]?T[a].forEach(d):(e.push(a),f[a]=!0))}var e=[],f={};b.forEach(d);throw new bb(a+": "+e.map(cb).join([", "]));}
function fb(a,b,d){switch(b){case 0:return d?function(a){return C[a]}:function(a){return A[a]};case 1:return d?function(a){return la[a>>1]}:function(a){return ma[a>>1]};case 2:return d?function(a){return D[a>>2]}:function(a){return E[a>>2]};default:throw new TypeError("Unknown integer type: "+a);}}for(var gb=Array(256),Z=0;256>Z;++Z)gb[Z]=String.fromCharCode(Z);Ja=gb;Na=c.BindingError=Ma("BindingError");Pa=c.InternalError=Ma("InternalError");
c.count_emval_handles=function(){for(var a=0,b=5;b<X.length;++b)void 0!==X[b]&&++a;return a};c.get_first_emval=function(){for(var a=5;a<X.length;++a)if(void 0!==X[a])return X[a];return null};bb=c.UnboundTypeError=Ma("UnboundTypeError");var hb=G;G=G+4+15&-16;I=hb;ra=sa=da(G);ta=ra+xa;ua=da(ta);D[I>>2]=ua;c.wasmTableSize=26;c.wasmMaxTableSize=26;c.I={};
c.J={e:y,q:function(){var a=c.usingWasm?65536:16777216,b=2147483648-a;if(D[I>>2]>b)return!1;var d=J;for(J=Math.max(J,16777216);J<D[I>>2];)536870912>=J?J=ka(2*J,a):J=Math.min(ka((3*J+2147483648)/4,a),b);a=c.reallocBuffer(J);if(!a||a.byteLength!=J)return J=d,!1;c.buffer=buffer=a;qa();return!0},m:function(){return J},l:function(){y("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value "+J+", (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime, or (3) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 ")},
g:function(a){c.___errno_location&&(D[c.___errno_location()>>2]=a);return a},k:function(a,b,d,e,f){var g=Ia(d);b=Q(b);W(a,{name:b,fromWireType:function(a){return!!a},toWireType:function(a,b){return b?e:f},argPackAdvance:8,readValueFromPointer:function(a){if(1===d)var e=C;else if(2===d)e=la;else if(4===d)e=D;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(e[a>>g])},D:null})},j:function(a,b){b=Q(b);W(a,{name:b,fromWireType:function(a){var b=X[a].value;4<a&&0===--X[a].L&&
(X[a]=void 0,Ra.push(a));return b},toWireType:function(a,b){return Sa(b)},argPackAdvance:8,readValueFromPointer:Ta,D:null})},f:function(a,b,d){d=Ia(d);b=Q(b);W(a,{name:b,fromWireType:function(a){return a},toWireType:function(a,b){if("number"!==typeof b&&"boolean"!==typeof b)throw new TypeError('Cannot convert "'+Ua(b)+'" to '+this.name);return b},argPackAdvance:8,readValueFromPointer:Va(b,d),D:null})},i:function(a,b,d,e,f,g){var h=$a(b,d);a=Q(a);f=ab(e,f);Za(a,function(){eb("Cannot call "+a+" due to unbound types",
h)},b-1);Qa(h,function(d){var e=[d[0],null].concat(d.slice(1)),m=d=a,h=f,k=e.length;2>k&&V("argTypes array size mismatch! Must at least get return value and 'this' types!");for(var na=null!==e[1]&&!1,P=!1,l=1;l<e.length;++l)if(null!==e[l]&&void 0===e[l].D){P=!0;break}var Ha="void"!==e[0].name,H="",L="";for(l=0;l<k-2;++l)H+=(0!==l?", ":"")+"arg"+l,L+=(0!==l?", ":"")+"arg"+l+"Wired";m="return function "+Ka(m)+"("+H+") {\nif (arguments.length !== "+(k-2)+") {\nthrowBindingError('function "+m+" called with ' + arguments.length + ' arguments, expected "+
(k-2)+" args!');\n}\n";P&&(m+="var destructors = [];\n");var Oa=P?"destructors":"null";H="throwBindingError invoker fn runDestructors retType classParam".split(" ");h=[V,h,g,Xa,e[0],e[1]];na&&(m+="var thisWired = classParam.toWireType("+Oa+", this);\n");for(l=0;l<k-2;++l)m+="var arg"+l+"Wired = argType"+l+".toWireType("+Oa+", arg"+l+"); // "+e[l+2].name+"\n",H.push("argType"+l),h.push(e[l+2]);na&&(L="thisWired"+(0<L.length?", ":"")+L);m+=(Ha?"var rv = ":"")+"invoker(fn"+(0<L.length?", ":"")+L+");\n";
if(P)m+="runDestructors(destructors);\n";else for(l=na?1:2;l<e.length;++l)k=1===l?"thisWired":"arg"+(l-2)+"Wired",null!==e[l].D&&(m+=k+"_dtor("+k+"); // "+e[l].name+"\n",H.push(k+"_dtor"),h.push(e[l].D));Ha&&(m+="var ret = retType.fromWireType(rv);\nreturn ret;\n");H.push(m+"}\n");e=Wa(H).apply(null,h);l=b-1;if(!c.hasOwnProperty(d))throw new Pa("Replacing nonexistant public symbol");void 0!==c[d].C&&void 0!==l?c[d].C[l]=e:(c[d]=e,c[d].H=l);return[]})},d:function(a,b,d,e,f){function g(a){return a}
b=Q(b);-1===f&&(f=4294967295);var h=Ia(d);if(0===e){var k=32-8*d;g=function(a){return a<<k>>>k}}var r=-1!=b.indexOf("unsigned");W(a,{name:b,fromWireType:g,toWireType:function(a,d){if("number"!==typeof d&&"boolean"!==typeof d)throw new TypeError('Cannot convert "'+Ua(d)+'" to '+this.name);if(d<e||d>f)throw new TypeError('Passing a number "'+Ua(d)+'" from JS side to C/C++ side to an argument of type "'+b+'", which is outside the valid range ['+e+", "+f+"]!");return r?d>>>0:d|0},argPackAdvance:8,readValueFromPointer:fb(b,
h,0!==e),D:null})},c:function(a,b,d){function e(a){a>>=2;var b=E;return new f(b.buffer,b[a+1],b[a])}var f=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];d=Q(d);W(a,{name:d,fromWireType:e,argPackAdvance:8,readValueFromPointer:e},{K:!0})},h:function(a,b){b=Q(b);var d="std::string"===b;W(a,{name:b,fromWireType:function(a){var b=E[a>>2];if(d){var e=A[a+4+b],h=0;0!=e&&(h=e,A[a+4+b]=0);var k=a+4;for(e=0;e<=b;++e){var r=a+4+e;if(0==A[r]){k=ia(k);if(void 0===
m)var m=k;else m+=String.fromCharCode(0),m+=k;k=r+1}}0!=h&&(A[a+4+b]=h)}else{m=Array(b);for(e=0;e<b;++e)m[e]=String.fromCharCode(A[a+4+e]);m=m.join("")}Y(a);return m},toWireType:function(a,b){b instanceof ArrayBuffer&&(b=new Uint8Array(b));var e="string"===typeof b;e||b instanceof Uint8Array||b instanceof Uint8ClampedArray||b instanceof Int8Array||V("Cannot pass non-string to std::string");var f=(d&&e?function(){for(var a=0,e=0;e<b.length;++e){var d=b.charCodeAt(e);55296<=d&&57343>=d&&(d=65536+((d&
1023)<<10)|b.charCodeAt(++e)&1023);127>=d?++a:a=2047>=d?a+2:65535>=d?a+3:2097151>=d?a+4:67108863>=d?a+5:a+6}return a}:function(){return b.length})(),k=ib(4+f+1);E[k>>2]=f;if(d&&e)ja(b,k+4,f+1);else if(e)for(e=0;e<f;++e){var r=b.charCodeAt(e);255<r&&(Y(k),V("String has UTF-16 code units that do not fit in 8 bits"));A[k+4+e]=r}else for(e=0;e<f;++e)A[k+4+e]=b[e];null!==a&&a.push(Y,k);return k},argPackAdvance:8,readValueFromPointer:Ta,D:function(a){Y(a)}})},p:function(a,b,d){d=Q(d);if(2===b){var e=function(){return ma};
var f=1}else 4===b&&(e=function(){return E},f=2);W(a,{name:d,fromWireType:function(a){for(var b=e(),d=E[a>>2],g=Array(d),m=a+4>>f,B=0;B<d;++B)g[B]=String.fromCharCode(b[m+B]);Y(a);return g.join("")},toWireType:function(a,d){var g=e(),h=d.length,m=ib(4+h*b);E[m>>2]=h;for(var B=m+4>>f,U=0;U<h;++U)g[B+U]=d.charCodeAt(U);null!==a&&a.push(Y,m);return m},argPackAdvance:8,readValueFromPointer:Ta,D:function(a){Y(a)}})},o:function(a,b){b=Q(b);W(a,{M:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},
n:function(a,b,d){A.set(A.subarray(b,b+d),a);return a},a:I,b:sa};var jb=c.asm(c.I,c.J,buffer);c.asm=jb;
var Fa=c.__GLOBAL__sub_I_bind_cpp=function(){return c.asm.r.apply(null,arguments)},Ga=c.__GLOBAL__sub_I_bind_cpp_2=function(){return c.asm.s.apply(null,arguments)},db=c.___getTypeName=function(){return c.asm.t.apply(null,arguments)},va=c._emscripten_replace_memory=function(){return c.asm._emscripten_replace_memory.apply(null,arguments)},Y=c._free=function(){return c.asm.u.apply(null,arguments)},ib=c._malloc=function(){return c.asm.v.apply(null,arguments)};
c.dynCall_iii=function(){return c.asm.w.apply(null,arguments)};c.dynCall_iiii=function(){return c.asm.x.apply(null,arguments)};c.dynCall_vi=function(){return c.asm.y.apply(null,arguments)};c.dynCall_viiii=function(){return c.asm.z.apply(null,arguments)};c.dynCall_viiiii=function(){return c.asm.A.apply(null,arguments)};c.dynCall_viiiiii=function(){return c.asm.B.apply(null,arguments)};c.asm=jb;c.UTF8ToString=function(a){return ia(a)};
c.then=function(a){if(c.calledRun)a(c);else{var b=c.onRuntimeInitialized;c.onRuntimeInitialized=function(){b&&b();a(c)}}return c};N=function kb(){c.calledRun||lb();c.calledRun||(N=kb)};
function lb(){function a(){if(!c.calledRun&&(c.calledRun=!0,!fa)){Ca||(Ca=!0,K(za));K(Aa);if(c.onRuntimeInitialized)c.onRuntimeInitialized();if(c.postRun)for("function"==typeof c.postRun&&(c.postRun=[c.postRun]);c.postRun.length;){var a=c.postRun.shift();Ba.unshift(a)}K(Ba)}}if(!(0<M)){if(c.preRun)for("function"==typeof c.preRun&&(c.preRun=[c.preRun]);c.preRun.length;)Da();K(ya);0<M||c.calledRun||(c.setStatus?(c.setStatus("Running..."),setTimeout(function(){setTimeout(function(){c.setStatus("")},
1);a()},1)):a())}}c.run=lb;function y(a){if(c.onAbort)c.onAbort(a);void 0!==a?(ca(a),z(a),a=JSON.stringify(a)):a="";fa=!0;throw"abort("+a+"). Build with -s ASSERTIONS=1 for more info.";}c.abort=y;if(c.preInit)for("function"==typeof c.preInit&&(c.preInit=[c.preInit]);0<c.preInit.length;)c.preInit.pop()();c.noExitRuntime=!0;lb();


  return Module;
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
    module.exports = Module;
  else if (typeof define === 'function' && define['amd'])
    define([], function() { return Module; });
  else if (typeof exports === 'object')
    exports["Module"] = Module;
  