
var Module = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  return (
function(Module) {
  Module = Module || {};

var c;c||(c=typeof Module !== 'undefined' ? Module : {});var n={},q;for(q in c)c.hasOwnProperty(q)&&(n[q]=c[q]);c.arguments=[];c.thisProgram="./this.program";c.quit=function(a,b){throw b;};c.preRun=[];c.postRun=[];var r=!1,t=!1,v=!1,aa=!1;r="object"===typeof window;t="function"===typeof importScripts;v="object"===typeof process&&"function"===typeof require&&!r&&!t;aa=!r&&!v&&!t;var w="";function x(a){return c.locateFile?c.locateFile(a,w):w+a}
if(v){w=__dirname+"/";var y,z;c.read=function(a,b){y||(y=require("fs"));z||(z=require("path"));a=z.normalize(a);a=y.readFileSync(a);return b?a:a.toString()};c.readBinary=function(a){a=c.read(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&(c.thisProgram=process.argv[1].replace(/\\/g,"/"));c.arguments=process.argv.slice(2);process.on("uncaughtException",function(a){if(!(a instanceof A))throw a;});process.on("unhandledRejection",B);c.quit=function(a){process.exit(a)};
c.inspect=function(){return"[Emscripten Module object]"}}else if(aa)"undefined"!=typeof read&&(c.read=function(a){return read(a)}),c.readBinary=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?c.arguments=scriptArgs:"undefined"!=typeof arguments&&(c.arguments=arguments),"function"===typeof quit&&(c.quit=function(a){quit(a)});else if(r||t)t?w=self.location.href:document.currentScript&&
(w=document.currentScript.src),_scriptDir&&(w=_scriptDir),0!==w.indexOf("blob:")?w=w.substr(0,w.lastIndexOf("/")+1):w="",c.read=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},t&&(c.readBinary=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),c.readAsync=function(a,b,e){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||
0==d.status&&d.response?b(d.response):e()};d.onerror=e;d.send(null)},c.setWindowTitle=function(a){document.title=a};var C=c.print||("undefined"!==typeof console?console.log.bind(console):"undefined"!==typeof print?print:null),D=c.printErr||("undefined"!==typeof printErr?printErr:"undefined"!==typeof console&&console.warn.bind(console)||C);for(q in n)n.hasOwnProperty(q)&&(c[q]=n[q]);n=void 0;function ba(a){var b;b||(b=16);return Math.ceil(a/b)*b}
var ca={"f64-rem":function(a,b){return a%b},"debugger":function(){debugger}},tempRet0=0,E=!1;function assert(a,b){a||B("Assertion failed: "+b)}function da(a){var b=c["_"+a];assert(b,"Cannot call unknown function "+a+", make sure it is exported");return b}
var ja={stackSave:function(){ea()},stackRestore:function(){fa()},arrayToC:function(a){var b=ha(a.length);F.set(a,b);return b},stringToC:function(a){var b=0;if(null!==a&&void 0!==a&&0!==a){var e=(a.length<<2)+1;b=ha(e);ia(a,b,e)}return b}},ka={string:ja.stringToC,array:ja.arrayToC};
function la(a){var b;if(0===b||!a)return"";for(var e=0,d,f=0;;){d=G[a+f>>0];e|=d;if(0==d&&!b)break;f++;if(b&&f==b)break}b||(b=f);d="";if(128>e){for(;0<b;)e=String.fromCharCode.apply(String,G.subarray(a,a+Math.min(b,1024))),d=d?d+e:e,a+=1024,b-=1024;return d}return ma(a)}var na="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function oa(a,b){for(var e=b;a[e];)++e;if(16<e-b&&a.subarray&&na)return na.decode(a.subarray(b,e));for(e="";;){var d=a[b++];if(!d)return e;if(d&128){var f=a[b++]&63;if(192==(d&224))e+=String.fromCharCode((d&31)<<6|f);else{var g=a[b++]&63;if(224==(d&240))d=(d&15)<<12|f<<6|g;else{var k=a[b++]&63;if(240==(d&248))d=(d&7)<<18|f<<12|g<<6|k;else{var h=a[b++]&63;if(248==(d&252))d=(d&3)<<24|f<<18|g<<12|k<<6|h;else{var p=a[b++]&63;d=(d&1)<<30|f<<24|g<<18|k<<12|h<<6|p}}}65536>d?e+=String.fromCharCode(d):(d-=
65536,e+=String.fromCharCode(55296|d>>10,56320|d&1023))}}else e+=String.fromCharCode(d)}}function ma(a){return oa(G,a)}
function ia(a,b,e){var d=G;if(0<e){e=b+e-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var k=a.charCodeAt(++f);g=65536+((g&1023)<<10)|k&1023}if(127>=g){if(b>=e)break;d[b++]=g}else{if(2047>=g){if(b+1>=e)break;d[b++]=192|g>>6}else{if(65535>=g){if(b+2>=e)break;d[b++]=224|g>>12}else{if(2097151>=g){if(b+3>=e)break;d[b++]=240|g>>18}else{if(67108863>=g){if(b+4>=e)break;d[b++]=248|g>>24}else{if(b+5>=e)break;d[b++]=252|g>>30;d[b++]=128|g>>24&63}d[b++]=128|g>>18&63}d[b++]=128|g>>
12&63}d[b++]=128|g>>6&63}d[b++]=128|g&63}}d[b]=0}}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");function pa(a,b){0<a%b&&(a+=b-a%b);return a}var buffer,F,G,qa,ra,H,I,sa,ta;function ua(){c.HEAP8=F=new Int8Array(buffer);c.HEAP16=qa=new Int16Array(buffer);c.HEAP32=H=new Int32Array(buffer);c.HEAPU8=G=new Uint8Array(buffer);c.HEAPU16=ra=new Uint16Array(buffer);c.HEAPU32=I=new Uint32Array(buffer);c.HEAPF32=sa=new Float32Array(buffer);c.HEAPF64=ta=new Float64Array(buffer)}
var J,K,va,L,wa,xa,M;J=K=va=L=wa=xa=M=0;c.reallocBuffer||(c.reallocBuffer=function(a){try{var b=F;var e=new ArrayBuffer(a);(new Int8Array(e)).set(b)}catch(d){return!1}return ya(e)?e:!1});var za;try{za=Function.prototype.call.bind(Object.getOwnPropertyDescriptor(ArrayBuffer.prototype,"byteLength").get),za(new ArrayBuffer(4))}catch(a){za=function(b){return b.byteLength}}var Aa=c.TOTAL_STACK||5242880,N=c.TOTAL_MEMORY||16777216;
N<Aa&&D("TOTAL_MEMORY should be larger than TOTAL_STACK, was "+N+"! (TOTAL_STACK="+Aa+")");c.buffer?buffer=c.buffer:("object"===typeof WebAssembly&&"function"===typeof WebAssembly.Memory?(c.wasmMemory=new WebAssembly.Memory({initial:N/65536}),buffer=c.wasmMemory.buffer):buffer=new ArrayBuffer(N),c.buffer=buffer);ua();
function O(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var e=b.N;"number"===typeof e?void 0===b.I?c.dynCall_v(e):c.dynCall_vi(e,b.I):e(void 0===b.I?null:b.I)}}}var Ba=[],Ca=[],Da=[],Ea=[],Fa=[],Ga=!1;function Ha(){var a=c.preRun.shift();Ba.unshift(a)}var P=0,Ia=null,Q=null;c.preloadedImages={};c.preloadedAudios={};function R(a){return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}
(function(){function a(){try{if(c.wasmBinary)return new Uint8Array(c.wasmBinary);if(c.readBinary)return c.readBinary(f);throw"both async and sync fetching of the wasm failed";}catch(m){B(m)}}function b(){return c.wasmBinary||!r&&!t||"function"!==typeof fetch?new Promise(function(b){b(a())}):fetch(f,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+f+"'";return a.arrayBuffer()}).catch(function(){return a()})}function e(a){function d(a){h=a.exports;if(h.memory){a=
h.memory;var b=c.buffer;a.byteLength<b.byteLength&&D("the new buffer in mergeMemory is smaller than the previous one. in native wasm, we should grow memory here");b=new Int8Array(b);(new Int8Array(a)).set(b);c.buffer=buffer=a;ua()}c.asm=h;c.usingWasm=!0;P--;c.monitorRunDependencies&&c.monitorRunDependencies(P);0==P&&(null!==Ia&&(clearInterval(Ia),Ia=null),Q&&(a=Q,Q=null,a()))}function e(a){d(a.instance)}function g(a){b().then(function(a){return WebAssembly.instantiate(a,k)}).then(a,function(a){D("failed to asynchronously prepare wasm: "+
a);B(a)})}if("object"!==typeof WebAssembly)return D("no native wasm support detected"),!1;if(!(c.wasmMemory instanceof WebAssembly.Memory))return D("no native wasm Memory in use"),!1;a.memory=c.wasmMemory;k.global={NaN:NaN,Infinity:Infinity};k["global.Math"]=Math;k.env=a;P++;c.monitorRunDependencies&&c.monitorRunDependencies(P);if(c.instantiateWasm)try{return c.instantiateWasm(k,d)}catch(Xa){return D("Module.instantiateWasm callback failed with error: "+Xa),!1}c.wasmBinary||"function"!==typeof WebAssembly.instantiateStreaming||
R(f)||"function"!==typeof fetch?g(e):WebAssembly.instantiateStreaming(fetch(f,{credentials:"same-origin"}),k).then(e,function(a){D("wasm streaming compile failed: "+a);D("falling back to ArrayBuffer instantiation");g(e)});return{}}var d="ColorQuantizer.wast",f="ColorQuantizer.wasm",g="ColorQuantizer.temp.asm.js";R(d)||(d=x(d));R(f)||(f=x(f));R(g)||(g=x(g));var k={global:null,env:null,asm2wasm:ca,parent:c},h=null;c.asmPreload=c.asm;var p=c.reallocBuffer;c.reallocBuffer=function(a){if("asmjs"===l)var b=
p(a);else a:{a=pa(a,c.usingWasm?65536:16777216);var d=c.buffer.byteLength;if(c.usingWasm)try{b=-1!==c.wasmMemory.grow((a-d)/65536)?c.buffer=c.wasmMemory.buffer:null;break a}catch(ib){b=null;break a}b=void 0}return b};var l="";c.asm=function(a,b){if(!b.table){a=c.wasmTableSize;void 0===a&&(a=1024);var d=c.wasmMaxTableSize;b.table="object"===typeof WebAssembly&&"function"===typeof WebAssembly.Table?void 0!==d?new WebAssembly.Table({initial:a,maximum:d,element:"anyfunc"}):new WebAssembly.Table({initial:a,
element:"anyfunc"}):Array(a);c.wasmTable=b.table}b.__memory_base||(b.__memory_base=c.STATIC_BASE);b.__table_base||(b.__table_base=0);b=e(b);assert(b,"no binaryen method succeeded.");return b}})();J=1024;K=J+7664;Ca.push({N:function(){Ja()}});c.STATIC_BASE=J;c.STATIC_BUMP=7664;var Ka=K;K+=16;var La=[null,[],[]],S=0;function T(){S+=4;return H[S-4>>2]}var Ma={};
function Na(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var Oa=void 0;function U(a){for(var b="";G[a];)b+=Oa[G[a++]];return b}var Pa={},Qa={},Ra={};function Sa(a,b){if(void 0===a)a="_unknown";else{a=a.replace(/[^a-zA-Z0-9_]/g,"$");var e=a.charCodeAt(0);a=48<=e&&57>=e?"_"+a:a}return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}
function Ta(a){var b=Error,e=Sa(a,function(b){this.name=a;this.message=b;b=Error(b).stack;void 0!==b&&(this.stack=this.toString()+"\n"+b.replace(/^Error(:[^\n]*)?\n/,""))});e.prototype=Object.create(b.prototype);e.prototype.constructor=e;e.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return e}var Ua=void 0;function V(a){throw new Ua(a);}
function W(a,b,e){e=e||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||V('type "'+d+'" must have a positive integer typeid pointer');if(Qa.hasOwnProperty(a)){if(e.R)return;V("Cannot register type '"+d+"' twice")}Qa[a]=b;delete Ra[a];Pa.hasOwnProperty(a)&&(b=Pa[a],delete Pa[a],b.forEach(function(a){a()}))}var Va=[],X=[{},{value:void 0},{value:null},{value:!0},{value:!1}];
function Wa(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=Va.length?Va.pop():X.length;X[b]={S:1,value:a};return b}}function Ya(a){return this.fromWireType(I[a>>2])}function Za(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}
function $a(a,b){switch(b){case 2:return function(a){return this.fromWireType(sa[a>>2])};case 3:return function(a){return this.fromWireType(ta[a>>3])};default:throw new TypeError("Unknown float type: "+a);}}
function ab(a,b,e){switch(b){case 0:return e?function(a){return F[a]}:function(a){return G[a]};case 1:return e?function(a){return qa[a>>1]}:function(a){return ra[a>>1]};case 2:return e?function(a){return H[a>>2]}:function(a){return I[a>>2]};default:throw new TypeError("Unknown integer type: "+a);}}for(var bb=Array(256),Y=0;256>Y;++Y)bb[Y]=String.fromCharCode(Y);Oa=bb;Ua=c.BindingError=Ta("BindingError");c.InternalError=Ta("InternalError");
c.count_emval_handles=function(){for(var a=0,b=5;b<X.length;++b)void 0!==X[b]&&++a;return a};c.get_first_emval=function(){for(var a=5;a<X.length;++a)if(void 0!==X[a])return X[a];return null};var cb=K;K=K+4+15&-16;M=cb;va=L=ba(K);wa=va+Aa;xa=ba(wa);H[M>>2]=xa;c.wasmTableSize=30;c.wasmMaxTableSize=30;c.L={};
c.M={h:B,x:function(){var a=c.usingWasm?65536:16777216,b=2147483648-a;if(H[M>>2]>b)return!1;var e=N;for(N=Math.max(N,16777216);N<H[M>>2];)536870912>=N?N=pa(2*N,a):N=Math.min(pa((3*N+2147483648)/4,a),b);a=c.reallocBuffer(N);if(!a||a.byteLength!=N)return N=e,!1;c.buffer=buffer=a;ua();return!0},q:function(){return N},f:function(a){tempRet0=a},d:function(){return tempRet0},p:function(){B("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value "+
N+", (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime, or (3) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 ")},j:function(a){c.___errno_location&&(H[c.___errno_location()>>2]=a);return a},o:function(a,b){S=b;try{var e=Ma.O();T();var d=T(),f=T(),g=T();FS.U(e,d,g);H[f>>2]=e.position;e.P&&0===d&&0===g&&(e.P=null);return 0}catch(k){return"undefined"!==typeof FS&&k instanceof FS.J||B(k),-k.K}},i:function(a,b){S=b;
try{var e=T(),d=T(),f=T();for(b=a=0;b<f;b++){for(var g=H[d+8*b>>2],k=H[d+(8*b+4)>>2],h=0;h<k;h++){var p=e,l=G[g+h],m=La[p];assert(m);0===l||10===l?((1===p?C:D)(oa(m,0)),m.length=0):m.push(l)}a+=k}return a}catch(u){return"undefined"!==typeof FS&&u instanceof FS.J||B(u),-u.K}},n:function(a,b){S=b;return 0},w:function(a,b){S=b;try{var e=Ma.O();FS.close(e);return 0}catch(d){return"undefined"!==typeof FS&&d instanceof FS.J||B(d),-d.K}},v:function(a,b,e,d,f){var g=Na(e);b=U(b);W(a,{name:b,fromWireType:function(a){return!!a},
toWireType:function(a,b){return b?d:f},argPackAdvance:8,readValueFromPointer:function(a){if(1===e)var d=F;else if(2===e)d=qa;else if(4===e)d=H;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(d[a>>g])},H:null})},u:function(a,b){b=U(b);W(a,{name:b,fromWireType:function(a){var b=X[a].value;4<a&&0===--X[a].S&&(X[a]=void 0,Va.push(a));return b},toWireType:function(a,b){return Wa(b)},argPackAdvance:8,readValueFromPointer:Ya,H:null})},m:function(a,b,e){e=Na(e);b=U(b);W(a,
{name:b,fromWireType:function(a){return a},toWireType:function(a,b){if("number"!==typeof b&&"boolean"!==typeof b)throw new TypeError('Cannot convert "'+Za(b)+'" to '+this.name);return b},argPackAdvance:8,readValueFromPointer:$a(b,e),H:null})},g:function(a,b,e,d,f){function g(a){return a}b=U(b);-1===f&&(f=4294967295);var k=Na(e);if(0===d){var h=32-8*e;g=function(a){return a<<h>>>h}}var p=-1!=b.indexOf("unsigned");W(a,{name:b,fromWireType:g,toWireType:function(a,e){if("number"!==typeof e&&"boolean"!==
typeof e)throw new TypeError('Cannot convert "'+Za(e)+'" to '+this.name);if(e<d||e>f)throw new TypeError('Passing a number "'+Za(e)+'" from JS side to C/C++ side to an argument of type "'+b+'", which is outside the valid range ['+d+", "+f+"]!");return p?e>>>0:e|0},argPackAdvance:8,readValueFromPointer:ab(b,k,0!==d),H:null})},e:function(a,b,e){function d(a){a>>=2;var b=I;return new f(b.buffer,b[a+1],b[a])}var f=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];
e=U(e);W(a,{name:e,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{R:!0})},l:function(a,b){b=U(b);var e="std::string"===b;W(a,{name:b,fromWireType:function(a){var b=I[a>>2];if(e){var d=G[a+4+b],k=0;0!=d&&(k=d,G[a+4+b]=0);var h=a+4;for(d=0;d<=b;++d){var p=a+4+d;if(0==G[p]){h=ma(h);if(void 0===l)var l=h;else l+=String.fromCharCode(0),l+=h;h=p+1}}0!=k&&(G[a+4+b]=k)}else{l=Array(b);for(d=0;d<b;++d)l[d]=String.fromCharCode(G[a+4+d]);l=l.join("")}Z(a);return l},toWireType:function(a,b){b instanceof
ArrayBuffer&&(b=new Uint8Array(b));var d="string"===typeof b;d||b instanceof Uint8Array||b instanceof Uint8ClampedArray||b instanceof Int8Array||V("Cannot pass non-string to std::string");var f=(e&&d?function(){for(var a=0,d=0;d<b.length;++d){var e=b.charCodeAt(d);55296<=e&&57343>=e&&(e=65536+((e&1023)<<10)|b.charCodeAt(++d)&1023);127>=e?++a:a=2047>=e?a+2:65535>=e?a+3:2097151>=e?a+4:67108863>=e?a+5:a+6}return a}:function(){return b.length})(),h=db(4+f+1);I[h>>2]=f;if(e&&d)ia(b,h+4,f+1);else if(d)for(d=
0;d<f;++d){var p=b.charCodeAt(d);255<p&&(Z(h),V("String has UTF-16 code units that do not fit in 8 bits"));G[h+4+d]=p}else for(d=0;d<f;++d)G[h+4+d]=b[d];null!==a&&a.push(Z,h);return h},argPackAdvance:8,readValueFromPointer:Ya,H:function(a){Z(a)}})},t:function(a,b,e){e=U(e);if(2===b){var d=function(){return ra};var f=1}else 4===b&&(d=function(){return I},f=2);W(a,{name:e,fromWireType:function(a){for(var b=d(),e=I[a>>2],g=Array(e),l=a+4>>f,m=0;m<e;++m)g[m]=String.fromCharCode(b[l+m]);Z(a);return g.join("")},
toWireType:function(a,e){var g=d(),k=e.length,l=db(4+k*b);I[l>>2]=k;for(var m=l+4>>f,u=0;u<k;++u)g[m+u]=e.charCodeAt(u);null!==a&&a.push(Z,l);return l},argPackAdvance:8,readValueFromPointer:Ya,H:function(a){Z(a)}})},s:function(a,b){b=U(b);W(a,{T:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},r:function(a,b,e){G.set(G.subarray(b,b+e),a);return a},k:function(a){if(!c.noExitRuntime&&(E=!0,L=eb,O(Ea),c.onExit))c.onExit(a);c.quit(a,new A(a))},a:M,b:Ka,c:L};
var fb=c.asm(c.L,c.M,buffer);c.asm=fb;var Ja=c.__GLOBAL__sub_I_bind_cpp=function(){return c.asm.y.apply(null,arguments)};c.___getTypeName=function(){return c.asm.z.apply(null,arguments)};var ya=c._emscripten_replace_memory=function(){return c.asm._emscripten_replace_memory.apply(null,arguments)},Z=c._free=function(){return c.asm.A.apply(null,arguments)};c._getImageThemeColor=function(){return c.asm.B.apply(null,arguments)};
var db=c._malloc=function(){return c.asm.C.apply(null,arguments)},ha=c.stackAlloc=function(){return c.asm.E.apply(null,arguments)},fa=c.stackRestore=function(){return c.asm.F.apply(null,arguments)},ea=c.stackSave=function(){return c.asm.G.apply(null,arguments)};c.dynCall_vi=function(){return c.asm.D.apply(null,arguments)};c.asm=fb;
c.cwrap=function(a,b,e,d){e=e||[];var f=e.every(function(a){return"number"===a});return"string"!==b&&f&&!d?da(a):function(){var d=e,f=arguments,h=da(a),p=[],l=0;if(f)for(var m=0;m<f.length;m++){var u=ka[d[m]];u?(0===l&&(l=ea()),p[m]=u(f[m])):p[m]=f[m]}d=h.apply(null,p);d="string"===b?la(d):"boolean"===b?!!d:d;0!==l&&fa(l);return d}};c.UTF8ToString=ma;c.then=function(a){if(c.calledRun)a(c);else{var b=c.onRuntimeInitialized;c.onRuntimeInitialized=function(){b&&b();a(c)}}return c};
function A(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}A.prototype=Error();A.prototype.constructor=A;var eb;Q=function gb(){c.calledRun||hb();c.calledRun||(Q=gb)};
function hb(){function a(){if(!c.calledRun&&(c.calledRun=!0,!E)){Ga||(Ga=!0,O(Ca));O(Da);if(c.onRuntimeInitialized)c.onRuntimeInitialized();if(c.postRun)for("function"==typeof c.postRun&&(c.postRun=[c.postRun]);c.postRun.length;){var a=c.postRun.shift();Fa.unshift(a)}O(Fa)}}if(!(0<P)){if(c.preRun)for("function"==typeof c.preRun&&(c.preRun=[c.preRun]);c.preRun.length;)Ha();O(Ba);0<P||c.calledRun||(c.setStatus?(c.setStatus("Running..."),setTimeout(function(){setTimeout(function(){c.setStatus("")},1);
a()},1)):a())}}c.run=hb;function B(a){if(c.onAbort)c.onAbort(a);void 0!==a?(C(a),D(a),a=JSON.stringify(a)):a="";E=!0;throw"abort("+a+"). Build with -s ASSERTIONS=1 for more info.";}c.abort=B;if(c.preInit)for("function"==typeof c.preInit&&(c.preInit=[c.preInit]);0<c.preInit.length;)c.preInit.pop()();c.noExitRuntime=!0;hb();


  return Module;
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
    module.exports = Module;
  else if (typeof define === 'function' && define['amd'])
    define([], function() { return Module; });
  else if (typeof exports === 'object')
    exports["Module"] = Module;
  