
var Module = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  return (
function(Module) {
  Module = Module || {};

var e;e||(e=typeof Module !== 'undefined' ? Module : {});var aa={},p;for(p in e)e.hasOwnProperty(p)&&(aa[p]=e[p]);e.arguments=[];e.thisProgram="./this.program";e.quit=function(a,b){throw b;};e.preRun=[];e.postRun=[];var ba=!1,q=!1,ca=!1,da=!1;ba="object"===typeof window;q="function"===typeof importScripts;ca="object"===typeof process&&"function"===typeof require&&!ba&&!q;da=!ba&&!ca&&!q;var t="";function ea(a){return e.locateFile?e.locateFile(a,t):t+a}
if(ca){t=__dirname+"/";var fa,ha;e.read=function(a,b){fa||(fa=require("fs"));ha||(ha=require("path"));a=ha.normalize(a);a=fa.readFileSync(a);return b?a:a.toString()};e.readBinary=function(a){a=e.read(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&(e.thisProgram=process.argv[1].replace(/\\/g,"/"));e.arguments=process.argv.slice(2);process.on("uncaughtException",function(a){throw a;});process.on("unhandledRejection",u);e.quit=function(a){process.exit(a)};e.inspect=
function(){return"[Emscripten Module object]"}}else if(da)"undefined"!=typeof read&&(e.read=function(a){return read(a)}),e.readBinary=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?e.arguments=scriptArgs:"undefined"!=typeof arguments&&(e.arguments=arguments),"function"===typeof quit&&(e.quit=function(a){quit(a)});else if(ba||q)q?t=self.location.href:document.currentScript&&(t=
document.currentScript.src),_scriptDir&&(t=_scriptDir),0!==t.indexOf("blob:")?t=t.substr(0,t.lastIndexOf("/")+1):t="",e.read=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},q&&(e.readBinary=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),e.readAsync=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||
0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)},e.setWindowTitle=function(a){document.title=a};var ia=e.print||("undefined"!==typeof console?console.log.bind(console):"undefined"!==typeof print?print:null),v=e.printErr||("undefined"!==typeof printErr?printErr:"undefined"!==typeof console&&console.warn.bind(console)||ia);for(p in aa)aa.hasOwnProperty(p)&&(e[p]=aa[p]);aa=void 0;function ja(a){var b;b||(b=16);return Math.ceil(a/b)*b}
var ka={"f64-rem":function(a,b){return a%b},"debugger":function(){debugger}},tempRet0=0,la=!1;function assert(a,b){a||u("Assertion failed: "+b)}function ma(a){var b=e["_"+a];assert(b,"Cannot call unknown function "+a+", make sure it is exported");return b}
var ra={stackSave:function(){na()},stackRestore:function(){oa()},arrayToC:function(a){var b=pa(a.length);w.set(a,b);return b},stringToC:function(a){var b=0;if(null!==a&&void 0!==a&&0!==a){var c=(a.length<<2)+1;b=pa(c);qa(a,x,b,c)}return b}},sa={string:ra.stringToC,array:ra.arrayToC};
function ta(a){var b;if(0===b||!a)return"";for(var c=0,d,f=0;;){d=x[a+f>>0];c|=d;if(0==d&&!b)break;f++;if(b&&f==b)break}b||(b=f);d="";if(128>c){for(;0<b;)c=String.fromCharCode.apply(String,x.subarray(a,a+Math.min(b,1024))),d=d?d+c:c,a+=1024,b-=1024;return d}return ua(a)}var va="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function wa(a,b){for(var c=b;a[c];)++c;if(16<c-b&&a.subarray&&va)return va.decode(a.subarray(b,c));for(c="";;){var d=a[b++];if(!d)return c;if(d&128){var f=a[b++]&63;if(192==(d&224))c+=String.fromCharCode((d&31)<<6|f);else{var g=a[b++]&63;if(224==(d&240))d=(d&15)<<12|f<<6|g;else{var h=a[b++]&63;if(240==(d&248))d=(d&7)<<18|f<<12|g<<6|h;else{var k=a[b++]&63;if(248==(d&252))d=(d&3)<<24|f<<18|g<<12|h<<6|k;else{var n=a[b++]&63;d=(d&1)<<30|f<<24|g<<18|h<<12|k<<6|n}}}65536>d?c+=String.fromCharCode(d):(d-=
65536,c+=String.fromCharCode(55296|d>>10,56320|d&1023))}}else c+=String.fromCharCode(d)}}function ua(a){return wa(x,a)}
function qa(a,b,c,d){if(0<d){d=c+d-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var h=a.charCodeAt(++f);g=65536+((g&1023)<<10)|h&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(2097151>=g){if(c+3>=d)break;b[c++]=240|g>>18}else{if(67108863>=g){if(c+4>=d)break;b[c++]=248|g>>24}else{if(c+5>=d)break;b[c++]=252|g>>30;b[c++]=128|g>>24&63}b[c++]=128|g>>18&63}b[c++]=128|g>>12&63}b[c++]=
128|g>>6&63}b[c++]=128|g&63}}b[c]=0}}function xa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:2097151>=d?b+4:67108863>=d?b+5:b+6}return b}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");function ya(a,b){0<a%b&&(a+=b-a%b);return a}var buffer,w,x,za,Aa,y,z,Ba,Ca;
function Da(){e.HEAP8=w=new Int8Array(buffer);e.HEAP16=za=new Int16Array(buffer);e.HEAP32=y=new Int32Array(buffer);e.HEAPU8=x=new Uint8Array(buffer);e.HEAPU16=Aa=new Uint16Array(buffer);e.HEAPU32=z=new Uint32Array(buffer);e.HEAPF32=Ba=new Float32Array(buffer);e.HEAPF64=Ca=new Float64Array(buffer)}var Ea,A,Fa,Ga,Ha,Ia,B;Ea=A=Fa=Ga=Ha=Ia=B=0;e.reallocBuffer||(e.reallocBuffer=function(a){try{var b=w;var c=new ArrayBuffer(a);(new Int8Array(c)).set(b)}catch(d){return!1}return Ja(c)?c:!1});var Ka;
try{Ka=Function.prototype.call.bind(Object.getOwnPropertyDescriptor(ArrayBuffer.prototype,"byteLength").get),Ka(new ArrayBuffer(4))}catch(a){Ka=function(b){return b.byteLength}}var La=e.TOTAL_STACK||5242880,C=e.TOTAL_MEMORY||16777216;C<La&&v("TOTAL_MEMORY should be larger than TOTAL_STACK, was "+C+"! (TOTAL_STACK="+La+")");
e.buffer?buffer=e.buffer:("object"===typeof WebAssembly&&"function"===typeof WebAssembly.Memory?(e.wasmMemory=new WebAssembly.Memory({initial:C/65536}),buffer=e.wasmMemory.buffer):buffer=new ArrayBuffer(C),e.buffer=buffer);Da();function Ma(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var c=b.fb;"number"===typeof c?void 0===b.kb?e.dynCall_v(c):e.dynCall_vi(c,b.kb):c(void 0===b.kb?null:b.kb)}}}var Na=[],Oa=[],Pa=[],Qa=[],Ra=!1;
function Sa(){var a=e.preRun.shift();Na.unshift(a)}var D=0,Ta=null,Ua=null;e.preloadedImages={};e.preloadedAudios={};function Va(a){return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}
(function(){function a(){try{if(e.wasmBinary)return new Uint8Array(e.wasmBinary);if(e.readBinary)return e.readBinary(f);throw"both async and sync fetching of the wasm failed";}catch(m){u(m)}}function b(){return e.wasmBinary||!ba&&!q||"function"!==typeof fetch?new Promise(function(b){b(a())}):fetch(f,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+f+"'";return a.arrayBuffer()}).catch(function(){return a()})}function c(a){function c(a){k=a.exports;
if(k.memory){a=k.memory;var b=e.buffer;a.byteLength<b.byteLength&&v("the new buffer in mergeMemory is smaller than the previous one. in native wasm, we should grow memory here");b=new Int8Array(b);(new Int8Array(a)).set(b);e.buffer=buffer=a;Da()}e.asm=k;e.usingWasm=!0;D--;e.monitorRunDependencies&&e.monitorRunDependencies(D);0==D&&(null!==Ta&&(clearInterval(Ta),Ta=null),Ua&&(a=Ua,Ua=null,a()))}function d(a){c(a.instance)}function g(a){b().then(function(a){return WebAssembly.instantiate(a,h)}).then(a,
function(a){v("failed to asynchronously prepare wasm: "+a);u(a)})}if("object"!==typeof WebAssembly)return v("no native wasm support detected"),!1;if(!(e.wasmMemory instanceof WebAssembly.Memory))return v("no native wasm Memory in use"),!1;a.memory=e.wasmMemory;h.global={NaN:NaN,Infinity:Infinity};h["global.Math"]=Math;h.env=a;D++;e.monitorRunDependencies&&e.monitorRunDependencies(D);if(e.instantiateWasm)try{return e.instantiateWasm(h,c)}catch(Qb){return v("Module.instantiateWasm callback failed with error: "+
Qb),!1}e.wasmBinary||"function"!==typeof WebAssembly.instantiateStreaming||Va(f)||"function"!==typeof fetch?g(d):WebAssembly.instantiateStreaming(fetch(f,{credentials:"same-origin"}),h).then(d,function(a){v("wasm streaming compile failed: "+a);v("falling back to ArrayBuffer instantiation");g(d)});return{}}var d="tt.wast",f="tt.wasm",g="tt.temp.asm.js";Va(d)||(d=ea(d));Va(f)||(f=ea(f));Va(g)||(g=ea(g));var h={global:null,env:null,asm2wasm:ka,parent:e},k=null;e.asmPreload=e.asm;var n=e.reallocBuffer;
e.reallocBuffer=function(a){if("asmjs"===l)var b=n(a);else a:{a=ya(a,e.usingWasm?65536:16777216);var c=e.buffer.byteLength;if(e.usingWasm)try{b=-1!==e.wasmMemory.grow((a-c)/65536)?e.buffer=e.wasmMemory.buffer:null;break a}catch(F){b=null;break a}b=void 0}return b};var l="";e.asm=function(a,b){if(!b.table){a=e.wasmTableSize;void 0===a&&(a=1024);var d=e.wasmMaxTableSize;b.table="object"===typeof WebAssembly&&"function"===typeof WebAssembly.Table?void 0!==d?new WebAssembly.Table({initial:a,maximum:d,
element:"anyfunc"}):new WebAssembly.Table({initial:a,element:"anyfunc"}):Array(a);e.wasmTable=b.table}b.__memory_base||(b.__memory_base=e.STATIC_BASE);b.__table_base||(b.__table_base=0);b=c(b);assert(b,"no binaryen method succeeded.");return b}})();Ea=1024;A=Ea+25376;Oa.push({fb:function(){Wa()}},{fb:function(){Xa()}},{fb:function(){Ya()}},{fb:function(){Za()}});e.STATIC_BASE=Ea;e.STATIC_BUMP=25376;var $a=A;A+=16;function ab(a){e.___errno_location&&(y[e.___errno_location()>>2]=a);return a}
var bb=[null,[],[]],E=0;function G(){E+=4;return y[E-4>>2]}var H={},cb={};function I(a){for(;a.length;){var b=a.pop();a.pop()(b)}}function J(a){return this.fromWireType(z[a>>2])}var K={},L={},db={};function eb(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}function fb(a,b){a=eb(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}
function gb(a){var b=Error,c=fb(a,function(b){this.name=a;this.message=b;b=Error(b).stack;void 0!==b&&(this.stack=this.toString()+"\n"+b.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}var hb=void 0;function ib(a){throw new hb(a);}
function M(a,b,c){function d(b){b=c(b);b.length!==a.length&&ib("Mismatched type converter count");for(var d=0;d<a.length;++d)N(a[d],b[d])}a.forEach(function(a){db[a]=b});var f=Array(b.length),g=[],h=0;b.forEach(function(a,b){L.hasOwnProperty(a)?f[b]=L[a]:(g.push(a),K.hasOwnProperty(a)||(K[a]=[]),K[a].push(function(){f[b]=L[a];++h;h===g.length&&d(f)}))});0===g.length&&d(f)}var jb={};
function kb(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var lb=void 0;function O(a){for(var b="";x[a];)b+=lb[x[a++]];return b}var P=void 0;function Q(a){throw new P(a);}
function N(a,b,c){c=c||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||Q('type "'+d+'" must have a positive integer typeid pointer');if(L.hasOwnProperty(a)){if(c.Fb)return;Q("Cannot register type '"+d+"' twice")}L[a]=b;delete db[a];K.hasOwnProperty(a)&&(b=K[a],delete K[a],b.forEach(function(a){a()}))}function mb(a){Q(a.Ia.La.Ja.name+" instance already deleted")}var nb=void 0,ob=[];
function pb(){for(;ob.length;){var a=ob.pop();a.Ia.Za=!1;a["delete"]()}}function R(){}var qb={};function rb(a,b,c){if(void 0===a[b].Ma){var d=a[b];a[b]=function(){a[b].Ma.hasOwnProperty(arguments.length)||Q("Function '"+c+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+a[b].Ma+")!");return a[b].Ma[arguments.length].apply(this,arguments)};a[b].Ma=[];a[b].Ma[d.Ya]=d}}
function sb(a,b,c){e.hasOwnProperty(a)?((void 0===c||void 0!==e[a].Ma&&void 0!==e[a].Ma[c])&&Q("Cannot register public name '"+a+"' twice"),rb(e,a,a),e.hasOwnProperty(c)&&Q("Cannot register multiple overloads of a function with the same number of arguments ("+c+")!"),e[a].Ma[c]=b):(e[a]=b,void 0!==c&&(e[a].$b=c))}function tb(a,b,c,d,f,g,h,k){this.name=a;this.constructor=b;this.Ua=c;this.Ra=d;this.Ta=f;this.Cb=g;this.bb=h;this.Ab=k;this.Ib=[]}
function ub(a,b,c){for(;b!==c;)b.bb||Q("Expected null or instance of "+c.name+", got an instance of "+b.name),a=b.bb(a),b=b.Ta;return a}function vb(a,b){if(null===b)return this.ob&&Q("null is not a valid "+this.name),0;b.Ia||Q('Cannot pass "'+S(b)+'" as a '+this.name);b.Ia.Ka||Q("Cannot pass deleted object as a pointer of type "+this.name);return ub(b.Ia.Ka,b.Ia.La.Ja,this.Ja)}
function wb(a,b){if(null===b){this.ob&&Q("null is not a valid "+this.name);if(this.hb){var c=this.ab();null!==a&&a.push(this.Ra,c);return c}return 0}b.Ia||Q('Cannot pass "'+S(b)+'" as a '+this.name);b.Ia.Ka||Q("Cannot pass deleted object as a pointer of type "+this.name);!this.gb&&b.Ia.La.gb&&Q("Cannot convert argument of type "+(b.Ia.Sa?b.Ia.Sa.name:b.Ia.La.name)+" to parameter type "+this.name);c=ub(b.Ia.Ka,b.Ia.La.Ja,this.Ja);if(this.hb)switch(void 0===b.Ia.Pa&&Q("Passing raw pointer to smart pointer is illegal"),
this.Lb){case 0:b.Ia.Sa===this?c=b.Ia.Pa:Q("Cannot convert argument of type "+(b.Ia.Sa?b.Ia.Sa.name:b.Ia.La.name)+" to parameter type "+this.name);break;case 1:c=b.Ia.Pa;break;case 2:if(b.Ia.Sa===this)c=b.Ia.Pa;else{var d=b.clone();c=this.Jb(c,xb(function(){d["delete"]()}));null!==a&&a.push(this.Ra,c)}break;default:Q("Unsupporting sharing policy")}return c}
function yb(a,b){if(null===b)return this.ob&&Q("null is not a valid "+this.name),0;b.Ia||Q('Cannot pass "'+S(b)+'" as a '+this.name);b.Ia.Ka||Q("Cannot pass deleted object as a pointer of type "+this.name);b.Ia.La.gb&&Q("Cannot convert argument of type "+b.Ia.La.name+" to parameter type "+this.name);return ub(b.Ia.Ka,b.Ia.La.Ja,this.Ja)}function zb(a,b,c){if(b===c)return a;if(void 0===c.Ta)return null;a=zb(a,b,c.Ta);return null===a?null:c.Ab(a)}var Ab={};
function Bb(a,b){for(void 0===b&&Q("ptr should not be undefined");a.Ta;)b=a.bb(b),a=a.Ta;return Ab[b]}function Cb(a,b){b.La&&b.Ka||ib("makeClassHandle requires ptr and ptrType");!!b.Sa!==!!b.Pa&&ib("Both smartPtrType and smartPtr must be specified");b.count={value:1};return Object.create(a,{Ia:{value:b}})}
function T(a,b,c,d,f,g,h,k,n,l,m){this.name=a;this.Ja=b;this.ob=c;this.gb=d;this.hb=f;this.Hb=g;this.Lb=h;this.vb=k;this.ab=n;this.Jb=l;this.Ra=m;f||void 0!==b.Ta?this.toWireType=wb:(this.toWireType=d?vb:yb,this.Qa=null)}function Db(a,b,c){e.hasOwnProperty(a)||ib("Replacing nonexistant public symbol");void 0!==e[a].Ma&&void 0!==c?e[a].Ma[c]=b:(e[a]=b,e[a].Ya=c)}
function V(a,b){a=O(a);if(void 0!==e["FUNCTION_TABLE_"+a])var c=e["FUNCTION_TABLE_"+a][b];else if("undefined"!==typeof FUNCTION_TABLE)c=FUNCTION_TABLE[b];else{c=e["dynCall_"+a];void 0===c&&(c=e["dynCall_"+a.replace(/f/g,"d")],void 0===c&&Q("No dynCall invoker for signature: "+a));for(var d=[],f=1;f<a.length;++f)d.push("a"+f);f="return function "+("dynCall_"+a+"_"+b)+"("+d.join(", ")+") {\n";f+="    return dynCall(rawFunction"+(d.length?", ":"")+d.join(", ")+");\n";c=(new Function("dynCall","rawFunction",
f+"};\n"))(c,b)}"function"!==typeof c&&Q("unknown function pointer with signature "+a+": "+b);return c}var Eb=void 0;function Fb(a){a=Gb(a);var b=O(a);W(a);return b}function X(a,b){function c(a){f[a]||L[a]||(db[a]?db[a].forEach(c):(d.push(a),f[a]=!0))}var d=[],f={};b.forEach(c);throw new Eb(a+": "+d.map(Fb).join([", "]));}
function Hb(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=fb(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
function Ib(a,b,c,d,f){var g=b.length;2>g&&Q("argTypes array size mismatch! Must at least get return value and 'this' types!");var h=null!==b[1]&&null!==c,k=!1;for(c=1;c<b.length;++c)if(null!==b[c]&&void 0===b[c].Qa){k=!0;break}var n="void"!==b[0].name,l="",m="";for(c=0;c<g-2;++c)l+=(0!==c?", ":"")+"arg"+c,m+=(0!==c?", ":"")+"arg"+c+"Wired";a="return function "+eb(a)+"("+l+") {\nif (arguments.length !== "+(g-2)+") {\nthrowBindingError('function "+a+" called with ' + arguments.length + ' arguments, expected "+
(g-2)+" args!');\n}\n";k&&(a+="var destructors = [];\n");var r=k?"destructors":"null";l="throwBindingError invoker fn runDestructors retType classParam".split(" ");d=[Q,d,f,I,b[0],b[1]];h&&(a+="var thisWired = classParam.toWireType("+r+", this);\n");for(c=0;c<g-2;++c)a+="var arg"+c+"Wired = argType"+c+".toWireType("+r+", arg"+c+"); // "+b[c+2].name+"\n",l.push("argType"+c),d.push(b[c+2]);h&&(m="thisWired"+(0<m.length?", ":"")+m);a+=(n?"var rv = ":"")+"invoker(fn"+(0<m.length?", ":"")+m+");\n";if(k)a+=
"runDestructors(destructors);\n";else for(c=h?1:2;c<b.length;++c)g=1===c?"thisWired":"arg"+(c-2)+"Wired",null!==b[c].Qa&&(a+=g+"_dtor("+g+"); // "+b[c].name+"\n",l.push(g+"_dtor"),d.push(b[c].Qa));n&&(a+="var ret = retType.fromWireType(rv);\nreturn ret;\n");l.push(a+"}\n");return Hb(l).apply(null,d)}function Jb(a,b){for(var c=[],d=0;d<a;d++)c.push(y[(b>>2)+d]);return c}
function Kb(a,b,c){a instanceof Object||Q(c+' with invalid "this": '+a);a instanceof b.Ja.constructor||Q(c+' incompatible with "this" of type '+a.constructor.name);a.Ia.Ka||Q("cannot call emscripten binding method "+c+" on deleted object");return ub(a.Ia.Ka,a.Ia.La.Ja,b.Ja)}var Lb=[],Y=[{},{value:void 0},{value:null},{value:!0},{value:!1}];function Mb(a){4<a&&0===--Y[a].Kb&&(Y[a]=void 0,Lb.push(a))}
function xb(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=Lb.length?Lb.pop():Y.length;Y[b]={Kb:1,value:a};return b}}function S(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}function Nb(a,b){switch(b){case 2:return function(a){return this.fromWireType(Ba[a>>2])};case 3:return function(a){return this.fromWireType(Ca[a>>3])};default:throw new TypeError("Unknown float type: "+a);}}
function Ob(a,b,c){switch(b){case 0:return c?function(a){return w[a]}:function(a){return x[a]};case 1:return c?function(a){return za[a>>1]}:function(a){return Aa[a>>1]};case 2:return c?function(a){return y[a>>2]}:function(a){return z[a>>2]};default:throw new TypeError("Unknown integer type: "+a);}}function Pb(a){a||Q("Cannot use deleted val. handle = "+a);return Y[a].value}var Sb={},Tb={};
function Ub(a){if(0===a)return 0;a=ta(a);if(!Tb.hasOwnProperty(a))return 0;Ub.Oa&&W(Ub.Oa);a=Tb[a];var b=xa(a)+1,c=Vb(b);c&&qa(a,w,c,b);Ub.Oa=c;return Ub.Oa}function Z(){Z.Oa||(Z.Oa=[]);Z.Oa.push(na());return Z.Oa.length-1}var Wb={},Xb=1;function Yb(a,b){Yb.Oa||(Yb.Oa={});a in Yb.Oa||(e.dynCall_v(b),Yb.Oa[a]=1)}function Zb(a){return 0===a%4&&(0!==a%100||0===a%400)}function $b(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}
var ac=[31,29,31,30,31,30,31,31,30,31,30,31],bc=[31,28,31,30,31,30,31,31,30,31,30,31];function cc(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(Zb(a.getFullYear())?ac:bc)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function dc(a,b,c,d){function f(a,b,c){for(a="number"===typeof a?a.toString():a||"";a.length<b;)a=c[0]+a;return a}function g(a,b){return f(a,b,"0")}function h(a,b){function c(a){return 0>a?-1:0<a?1:0}var d;0===(d=c(a.getFullYear()-b.getFullYear()))&&0===(d=c(a.getMonth()-b.getMonth()))&&(d=c(a.getDate()-b.getDate()));return d}function k(a){switch(a.getDay()){case 0:return new Date(a.getFullYear()-1,11,29);case 1:return a;case 2:return new Date(a.getFullYear(),0,3);case 3:return new Date(a.getFullYear(),
0,2);case 4:return new Date(a.getFullYear(),0,1);case 5:return new Date(a.getFullYear()-1,11,31);case 6:return new Date(a.getFullYear()-1,11,30)}}function n(a){a=cc(new Date(a.Na+1900,0,1),a.jb);var b=k(new Date(a.getFullYear()+1,0,4));return 0>=h(k(new Date(a.getFullYear(),0,4)),a)?0>=h(b,a)?a.getFullYear()+1:a.getFullYear():a.getFullYear()-1}var l=y[d+40>>2];d={Ob:y[d>>2],Nb:y[d+4>>2],ib:y[d+8>>2],Xa:y[d+12>>2],Va:y[d+16>>2],Na:y[d+20>>2],wb:y[d+24>>2],jb:y[d+28>>2],ac:y[d+32>>2],Mb:y[d+36>>2],
Pb:l?ta(l):""};c=ta(c);l={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S"};for(var m in l)c=c.replace(new RegExp(m,"g"),l[m]);var r="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),U="January February March April May June July August September October November December".split(" ");l={"%a":function(a){return r[a.wb].substring(0,3)},"%A":function(a){return r[a.wb]},"%b":function(a){return U[a.Va].substring(0,
3)},"%B":function(a){return U[a.Va]},"%C":function(a){return g((a.Na+1900)/100|0,2)},"%d":function(a){return g(a.Xa,2)},"%e":function(a){return f(a.Xa,2," ")},"%g":function(a){return n(a).toString().substring(2)},"%G":function(a){return n(a)},"%H":function(a){return g(a.ib,2)},"%I":function(a){a=a.ib;0==a?a=12:12<a&&(a-=12);return g(a,2)},"%j":function(a){return g(a.Xa+$b(Zb(a.Na+1900)?ac:bc,a.Va-1),3)},"%m":function(a){return g(a.Va+1,2)},"%M":function(a){return g(a.Nb,2)},"%n":function(){return"\n"},
"%p":function(a){return 0<=a.ib&&12>a.ib?"AM":"PM"},"%S":function(a){return g(a.Ob,2)},"%t":function(){return"\t"},"%u":function(a){return(new Date(a.Na+1900,a.Va+1,a.Xa,0,0,0,0)).getDay()||7},"%U":function(a){var b=new Date(a.Na+1900,0,1),c=0===b.getDay()?b:cc(b,7-b.getDay());a=new Date(a.Na+1900,a.Va,a.Xa);return 0>h(c,a)?g(Math.ceil((31-c.getDate()+($b(Zb(a.getFullYear())?ac:bc,a.getMonth()-1)-31)+a.getDate())/7),2):0===h(c,b)?"01":"00"},"%V":function(a){var b=k(new Date(a.Na+1900,0,4)),c=k(new Date(a.Na+
1901,0,4)),d=cc(new Date(a.Na+1900,0,1),a.jb);return 0>h(d,b)?"53":0>=h(c,d)?"01":g(Math.ceil((b.getFullYear()<a.Na+1900?a.jb+32-b.getDate():a.jb+1-b.getDate())/7),2)},"%w":function(a){return(new Date(a.Na+1900,a.Va+1,a.Xa,0,0,0,0)).getDay()},"%W":function(a){var b=new Date(a.Na,0,1),c=1===b.getDay()?b:cc(b,0===b.getDay()?1:7-b.getDay()+1);a=new Date(a.Na+1900,a.Va,a.Xa);return 0>h(c,a)?g(Math.ceil((31-c.getDate()+($b(Zb(a.getFullYear())?ac:bc,a.getMonth()-1)-31)+a.getDate())/7),2):0===h(c,b)?"01":
"00"},"%y":function(a){return(a.Na+1900).toString().substring(2)},"%Y":function(a){return a.Na+1900},"%z":function(a){a=a.Mb;var b=0<=a;a=Math.abs(a)/60;return(b?"+":"-")+String("0000"+(a/60*100+a%60)).slice(-4)},"%Z":function(a){return a.Pb},"%%":function(){return"%"}};for(m in l)0<=c.indexOf(m)&&(c=c.replace(new RegExp(m,"g"),l[m](d)));m=ec(c);if(m.length>b)return 0;w.set(m,a);return m.length-1}hb=e.InternalError=gb("InternalError");for(var fc=Array(256),hc=0;256>hc;++hc)fc[hc]=String.fromCharCode(hc);
lb=fc;P=e.BindingError=gb("BindingError");R.prototype.isAliasOf=function(a){if(!(this instanceof R&&a instanceof R))return!1;var b=this.Ia.La.Ja,c=this.Ia.Ka,d=a.Ia.La.Ja;for(a=a.Ia.Ka;b.Ta;)c=b.bb(c),b=b.Ta;for(;d.Ta;)a=d.bb(a),d=d.Ta;return b===d&&c===a};
R.prototype.clone=function(){this.Ia.Ka||mb(this);if(this.Ia.$a)return this.Ia.count.value+=1,this;var a=this.Ia;a=Object.create(Object.getPrototypeOf(this),{Ia:{value:{count:a.count,Za:a.Za,$a:a.$a,Ka:a.Ka,La:a.La,Pa:a.Pa,Sa:a.Sa}}});a.Ia.count.value+=1;a.Ia.Za=!1;return a};
R.prototype["delete"]=function(){this.Ia.Ka||mb(this);this.Ia.Za&&!this.Ia.$a&&Q("Object already scheduled for deletion");--this.Ia.count.value;if(0===this.Ia.count.value){var a=this.Ia;a.Pa?a.Sa.Ra(a.Pa):a.La.Ja.Ra(a.Ka)}this.Ia.$a||(this.Ia.Pa=void 0,this.Ia.Ka=void 0)};R.prototype.isDeleted=function(){return!this.Ia.Ka};
R.prototype.deleteLater=function(){this.Ia.Ka||mb(this);this.Ia.Za&&!this.Ia.$a&&Q("Object already scheduled for deletion");ob.push(this);1===ob.length&&nb&&nb(pb);this.Ia.Za=!0;return this};T.prototype.Db=function(a){this.vb&&(a=this.vb(a));return a};T.prototype.sb=function(a){this.Ra&&this.Ra(a)};T.prototype.argPackAdvance=8;T.prototype.readValueFromPointer=J;T.prototype.deleteObject=function(a){if(null!==a)a["delete"]()};
T.prototype.fromWireType=function(a){function b(){return this.hb?Cb(this.Ja.Ua,{La:this.Hb,Ka:c,Sa:this,Pa:a}):Cb(this.Ja.Ua,{La:this,Ka:a})}var c=this.Db(a);if(!c)return this.sb(a),null;var d=Bb(this.Ja,c);if(void 0!==d){if(0===d.Ia.count.value)return d.Ia.Ka=c,d.Ia.Pa=a,d.clone();d=d.clone();this.sb(a);return d}d=this.Ja.Cb(c);d=qb[d];if(!d)return b.call(this);d=this.gb?d.zb:d.pointerType;var f=zb(c,this.Ja,d.Ja);return null===f?b.call(this):this.hb?Cb(d.Ja.Ua,{La:d,Ka:f,Sa:this,Pa:a}):Cb(d.Ja.Ua,
{La:d,Ka:f})};e.getInheritedInstanceCount=function(){return Object.keys(Ab).length};e.getLiveInheritedInstances=function(){var a=[],b;for(b in Ab)Ab.hasOwnProperty(b)&&a.push(Ab[b]);return a};e.flushPendingDeletes=pb;e.setDelayFunction=function(a){nb=a;ob.length&&nb&&nb(pb)};Eb=e.UnboundTypeError=gb("UnboundTypeError");e.count_emval_handles=function(){for(var a=0,b=5;b<Y.length;++b)void 0!==Y[b]&&++a;return a};e.get_first_emval=function(){for(var a=5;a<Y.length;++a)if(void 0!==Y[a])return Y[a];return null};
var ic=A;A=A+4+15&-16;B=ic;Fa=Ga=ja(A);Ha=Fa+La;Ia=ja(Ha);y[B>>2]=Ia;function ec(a){var b=Array(xa(a)+1);qa(a,b,0,b.length);return b}e.wasmTableSize=496;e.wasmMaxTableSize=496;e.xb={};
e.yb={g:u,ba:function(){var a=e.usingWasm?65536:16777216,b=2147483648-a;if(y[B>>2]>b)return!1;var c=C;for(C=Math.max(C,16777216);C<y[B>>2];)536870912>=C?C=ya(2*C,a):C=Math.min(ya((3*C+2147483648)/4,a),b);a=e.reallocBuffer(C);if(!a||a.byteLength!=C)return C=c,!1;e.buffer=buffer=a;Da();return!0},U:function(){return C},f:function(a){tempRet0=a},d:function(){return tempRet0},B:function(){u("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value "+
C+", (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime, or (3) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 ")},x:function(){return!!jc.Qb},p:function(){},w:function(){ab(1);return-1},o:ab,aa:function(a,b){E=b;try{var c=H.ub();G();var d=G(),f=G(),g=G();FS.Xb(c,d,g);y[f>>2]=c.position;c.Eb&&0===d&&0===g&&(c.Eb=null);return 0}catch(h){return"undefined"!==typeof FS&&h instanceof FS.cb||u(h),-h.eb}},$:function(a,
b){E=b;try{var c=H.ub(),d=G(),f=G();return H.Tb(c,d,f)}catch(g){return"undefined"!==typeof FS&&g instanceof FS.cb||u(g),-g.eb}},v:function(a,b){E=b;try{var c=G(),d=G(),f=G();for(b=a=0;b<f;b++){for(var g=y[d+8*b>>2],h=y[d+(8*b+4)>>2],k=0;k<h;k++){var n=c,l=x[g+k],m=bb[n];assert(m);0===l||10===l?((1===n?ia:v)(wa(m,0)),m.length=0):m.push(l)}a+=h}return a}catch(r){return"undefined"!==typeof FS&&r instanceof FS.cb||u(r),-r.eb}},_:function(a,b){E=b;return 0},Z:function(a,b){E=b;try{var c=H.ub();FS.close(c);
return 0}catch(d){return"undefined"!==typeof FS&&d instanceof FS.cb||u(d),-d.eb}},Y:function(a,b){E=b;try{var c=G(),d=G(),f=H.Gb[c];if(!f)return 0;if(d===f.Wb){var g=FS.Ub(f.fd);H.Sb(c,g,d,f.flags);FS.Zb(g);H.Gb[c]=null;f.Rb&&W(f.Yb)}return 0}catch(h){return"undefined"!==typeof FS&&h instanceof FS.cb||u(h),-h.eb}},n:function(){},X:function(a){var b=cb[a];delete cb[a];var c=b.elements,d=c.length,f=c.map(function(a){return a.nb}).concat(c.map(function(a){return a.qb})),g=b.ab,h=b.Ra;M([a],f,function(a){c.forEach(function(b,
c){var g=a[c],f=b.lb,h=b.mb,k=a[c+d],l=b.pb,n=b.rb;b.read=function(a){return g.fromWireType(f(h,a))};b.write=function(a,b){var c=[];l(n,a,k.toWireType(c,b));I(c)}});return[{name:b.name,fromWireType:function(a){for(var b=Array(d),g=0;g<d;++g)b[g]=c[g].read(a);h(a);return b},toWireType:function(a,f){if(d!==f.length)throw new TypeError("Incorrect number of tuple elements for "+b.name+": expected="+d+", actual="+f.length);for(var m=g(),k=0;k<d;++k)c[k].write(m,f[k]);null!==a&&a.push(h,m);return m},argPackAdvance:8,
readValueFromPointer:J,Qa:h}]})},W:function(a){var b=jb[a];delete jb[a];var c=b.ab,d=b.Ra,f=b.tb,g=f.map(function(a){return a.nb}).concat(f.map(function(a){return a.qb}));M([a],g,function(a){var g={};f.forEach(function(b,c){var d=a[c],h=b.lb,k=b.mb,l=a[c+f.length],n=b.pb,Rb=b.rb;g[b.Bb]={read:function(a){return d.fromWireType(h(k,a))},write:function(a,b){var c=[];n(Rb,a,l.toWireType(c,b));I(c)}}});return[{name:b.name,fromWireType:function(a){var b={},c;for(c in g)b[c]=g[c].read(a);d(a);return b},
toWireType:function(a,b){for(var f in g)if(!(f in b))throw new TypeError("Missing field");var h=c();for(f in g)g[f].write(h,b[f]);null!==a&&a.push(d,h);return h},argPackAdvance:8,readValueFromPointer:J,Qa:d}]})},V:function(a,b,c,d,f){var g=kb(c);b=O(b);N(a,{name:b,fromWireType:function(a){return!!a},toWireType:function(a,b){return b?d:f},argPackAdvance:8,readValueFromPointer:function(a){if(1===c)var d=w;else if(2===c)d=za;else if(4===c)d=y;else throw new TypeError("Unknown boolean type size: "+b);
return this.fromWireType(d[a>>g])},Qa:null})},T:function(a,b,c,d,f,g,h,k,n,l,m,r,U){m=O(m);g=V(f,g);k&&(k=V(h,k));l&&(l=V(n,l));U=V(r,U);var F=eb(m);sb(F,function(){X("Cannot construct "+m+" due to unbound types",[d])});M([a,b,c],d?[d]:[],function(b){b=b[0];if(d){var c=b.Ja;var f=c.Ua}else f=R.prototype;b=fb(F,function(){if(Object.getPrototypeOf(this)!==h)throw new P("Use 'new' to construct "+m);if(void 0===n.Wa)throw new P(m+" has no accessible constructor");var a=n.Wa[arguments.length];if(void 0===
a)throw new P("Tried to invoke ctor of "+m+" with invalid number of parameters ("+arguments.length+") - expected ("+Object.keys(n.Wa).toString()+") parameters instead!");return a.apply(this,arguments)});var h=Object.create(f,{constructor:{value:b}});b.prototype=h;var n=new tb(m,b,h,U,c,g,k,l);c=new T(m,n,!0,!1,!1);f=new T(m+"*",n,!1,!1,!1);var r=new T(m+" const*",n,!1,!0,!1);qb[a]={pointerType:f,zb:r};Db(F,b);return[c,f,r]})},S:function(a,b,c,d,f,g,h){var k=Jb(c,d);b=O(b);g=V(f,g);M([],[a],function(a){function d(){X("Cannot call "+
f+" due to unbound types",k)}a=a[0];var f=a.name+"."+b,n=a.Ja.constructor;void 0===n[b]?(d.Ya=c-1,n[b]=d):(rb(n,b,f),n[b].Ma[c-1]=d);M([],k,function(a){a=[a[0],null].concat(a.slice(1));a=Ib(f,a,null,g,h);void 0===n[b].Ma?(a.Ya=c-1,n[b]=a):n[b].Ma[c-1]=a;return[]});return[]})},R:function(a,b,c,d,f,g){var h=Jb(b,c);f=V(d,f);M([],[a],function(a){a=a[0];var c="constructor "+a.name;void 0===a.Ja.Wa&&(a.Ja.Wa=[]);if(void 0!==a.Ja.Wa[b-1])throw new P("Cannot register multiple constructors with identical number of parameters ("+
(b-1)+") for class '"+a.name+"'! Overload resolution is currently only performed using the parameter count, not actual type info!");a.Ja.Wa[b-1]=function(){X("Cannot construct "+a.name+" due to unbound types",h)};M([],h,function(d){a.Ja.Wa[b-1]=function(){arguments.length!==b-1&&Q(c+" called with "+arguments.length+" arguments, expected "+(b-1));var a=[],h=Array(b);h[0]=g;for(var k=1;k<b;++k)h[k]=d[k].toWireType(a,arguments[k-1]);h=f.apply(null,h);I(a);return d[0].fromWireType(h)};return[]});return[]})},
Q:function(a,b,c,d,f,g,h,k){var n=Jb(c,d);b=O(b);g=V(f,g);M([],[a],function(a){function d(){X("Cannot call "+f+" due to unbound types",n)}a=a[0];var f=a.name+"."+b;k&&a.Ja.Ib.push(b);var l=a.Ja.Ua,F=l[b];void 0===F||void 0===F.Ma&&F.className!==a.name&&F.Ya===c-2?(d.Ya=c-2,d.className=a.name,l[b]=d):(rb(l,b,f),l[b].Ma[c-2]=d);M([],n,function(d){d=Ib(f,d,a,g,h);void 0===l[b].Ma?(d.Ya=c-2,l[b]=d):l[b].Ma[c-2]=d;return[]});return[]})},P:function(a,b,c,d,f,g,h,k,n,l){b=O(b);f=V(d,f);M([],[a],function(a){a=
a[0];var d=a.name+"."+b,m={get:function(){X("Cannot access "+d+" due to unbound types",[c,h])},enumerable:!0,configurable:!0};n?m.set=function(){X("Cannot access "+d+" due to unbound types",[c,h])}:m.set=function(){Q(d+" is a read-only property")};Object.defineProperty(a.Ja.Ua,b,m);M([],n?[c,h]:[c],function(c){var h=c[0],m={get:function(){var b=Kb(this,a,d+" getter");return h.fromWireType(f(g,b))},enumerable:!0};if(n){n=V(k,n);var r=c[1];m.set=function(b){var c=Kb(this,a,d+" setter"),g=[];n(l,c,r.toWireType(g,
b));I(g)}}Object.defineProperty(a.Ja.Ua,b,m);return[]});return[]})},O:function(a,b){b=O(b);N(a,{name:b,fromWireType:function(a){var b=Y[a].value;Mb(a);return b},toWireType:function(a,b){return xb(b)},argPackAdvance:8,readValueFromPointer:J,Qa:null})},u:function(a,b,c){c=kb(c);b=O(b);N(a,{name:b,fromWireType:function(a){return a},toWireType:function(a,b){if("number"!==typeof b&&"boolean"!==typeof b)throw new TypeError('Cannot convert "'+S(b)+'" to '+this.name);return b},argPackAdvance:8,readValueFromPointer:Nb(b,
c),Qa:null})},t:function(a,b,c,d,f,g){var h=Jb(b,c);a=O(a);f=V(d,f);sb(a,function(){X("Cannot call "+a+" due to unbound types",h)},b-1);M([],h,function(c){c=[c[0],null].concat(c.slice(1));Db(a,Ib(a,c,null,f,g),b-1);return[]})},i:function(a,b,c,d,f){function g(a){return a}b=O(b);-1===f&&(f=4294967295);var h=kb(c);if(0===d){var k=32-8*c;g=function(a){return a<<k>>>k}}var n=-1!=b.indexOf("unsigned");N(a,{name:b,fromWireType:g,toWireType:function(a,c){if("number"!==typeof c&&"boolean"!==typeof c)throw new TypeError('Cannot convert "'+
S(c)+'" to '+this.name);if(c<d||c>f)throw new TypeError('Passing a number "'+S(c)+'" from JS side to C/C++ side to an argument of type "'+b+'", which is outside the valid range ['+d+", "+f+"]!");return n?c>>>0:c|0},argPackAdvance:8,readValueFromPointer:Ob(b,h,0!==d),Qa:null})},h:function(a,b,c){function d(a){a>>=2;var b=z;return new f(b.buffer,b[a+1],b[a])}var f=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=O(c);N(a,{name:c,fromWireType:d,argPackAdvance:8,
readValueFromPointer:d},{Fb:!0})},s:function(a,b){b=O(b);var c="std::string"===b;N(a,{name:b,fromWireType:function(a){var b=z[a>>2];if(c){var d=x[a+4+b],h=0;0!=d&&(h=d,x[a+4+b]=0);var k=a+4;for(d=0;d<=b;++d){var n=a+4+d;if(0==x[n]){k=ua(k);if(void 0===l)var l=k;else l+=String.fromCharCode(0),l+=k;k=n+1}}0!=h&&(x[a+4+b]=h)}else{l=Array(b);for(d=0;d<b;++d)l[d]=String.fromCharCode(x[a+4+d]);l=l.join("")}W(a);return l},toWireType:function(a,b){b instanceof ArrayBuffer&&(b=new Uint8Array(b));var d="string"===
typeof b;d||b instanceof Uint8Array||b instanceof Uint8ClampedArray||b instanceof Int8Array||Q("Cannot pass non-string to std::string");var f=(c&&d?function(){return xa(b)}:function(){return b.length})(),k=Vb(4+f+1);z[k>>2]=f;if(c&&d)qa(b,x,k+4,f+1);else if(d)for(d=0;d<f;++d){var n=b.charCodeAt(d);255<n&&(W(k),Q("String has UTF-16 code units that do not fit in 8 bits"));x[k+4+d]=n}else for(d=0;d<f;++d)x[k+4+d]=b[d];null!==a&&a.push(W,k);return k},argPackAdvance:8,readValueFromPointer:J,Qa:function(a){W(a)}})},
N:function(a,b,c){c=O(c);if(2===b){var d=function(){return Aa};var f=1}else 4===b&&(d=function(){return z},f=2);N(a,{name:c,fromWireType:function(a){for(var b=d(),c=z[a>>2],g=Array(c),l=a+4>>f,m=0;m<c;++m)g[m]=String.fromCharCode(b[l+m]);W(a);return g.join("")},toWireType:function(a,c){var g=d(),h=c.length,l=Vb(4+h*b);z[l>>2]=h;for(var m=l+4>>f,r=0;r<h;++r)g[m+r]=c.charCodeAt(r);null!==a&&a.push(W,l);return l},argPackAdvance:8,readValueFromPointer:J,Qa:function(a){W(a)}})},M:function(a,b,c,d,f,g){cb[a]=
{name:O(b),ab:V(c,d),Ra:V(f,g),elements:[]}},r:function(a,b,c,d,f,g,h,k,n){cb[a].elements.push({nb:b,lb:V(c,d),mb:f,qb:g,pb:V(h,k),rb:n})},L:function(a,b,c,d,f,g){jb[a]={name:O(b),ab:V(c,d),Ra:V(f,g),tb:[]}},q:function(a,b,c,d,f,g,h,k,n,l){jb[a].tb.push({Bb:O(b),nb:c,lb:V(d,f),mb:g,qb:h,pb:V(k,n),rb:l})},K:function(a,b){b=O(b);N(a,{Vb:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},J:function(a,b,c){a=Pb(a);var d=L[b];void 0===d&&Q("emval::as has unknown type "+Fb(b));
b=d;d=[];var f=xb(d);y[c>>2]=f;return b.toWireType(d,a)},m:Mb,I:function(a,b){a=Pb(a);b=Pb(b);return xb(a[b])},H:function(a){var b=Sb[a];return xb(void 0===b?O(a):b)},G:function(a){I(Y[a].value);Mb(a)},e:function(){e.abort()},F:function(a,b,c){x.set(x.subarray(b,b+c),a);return a},l:Ub,k:function(a){var b=Z.Oa[a];Z.Oa.splice(a,1);oa(b)},j:Z,E:function(){return 0},D:function(a){return Wb[a]||0},C:function(a){if(0==a)return 22;y[a>>2]=Xb;Wb[Xb]=0;Xb++;return 0},A:Yb,z:function(a,b){if(!(a in Wb))return 22;
Wb[a]=b;return 0},y:function(a,b,c,d){return dc(a,b,c,d)},a:B,b:$a,c:Ga};var kc=e.asm(e.xb,e.yb,buffer);e.asm=kc;
var Wa=e.__GLOBAL__I_000101=function(){return e.asm.ca.apply(null,arguments)},Ya=e.__GLOBAL__sub_I_bind_cpp=function(){return e.asm.da.apply(null,arguments)},Za=e.__GLOBAL__sub_I_iostream_cpp=function(){return e.asm.ea.apply(null,arguments)},Xa=e.__GLOBAL__sub_I_tt_cpp=function(){return e.asm.fa.apply(null,arguments)},jc=e.__ZSt18uncaught_exceptionv=function(){return e.asm.ga.apply(null,arguments)},Gb=e.___getTypeName=function(){return e.asm.ha.apply(null,arguments)},Ja=e._emscripten_replace_memory=
function(){return e.asm._emscripten_replace_memory.apply(null,arguments)},W=e._free=function(){return e.asm.ia.apply(null,arguments)},Vb=e._malloc=function(){return e.asm.ja.apply(null,arguments)};e._showPtr=function(){return e.asm.ka.apply(null,arguments)};var pa=e.stackAlloc=function(){return e.asm.Fa.apply(null,arguments)},oa=e.stackRestore=function(){return e.asm.Ga.apply(null,arguments)},na=e.stackSave=function(){return e.asm.Ha.apply(null,arguments)};
e.dynCall_fii=function(){return e.asm.la.apply(null,arguments)};e.dynCall_i=function(){return e.asm.ma.apply(null,arguments)};e.dynCall_ii=function(){return e.asm.na.apply(null,arguments)};e.dynCall_iii=function(){return e.asm.oa.apply(null,arguments)};e.dynCall_iiii=function(){return e.asm.pa.apply(null,arguments)};e.dynCall_iiiii=function(){return e.asm.qa.apply(null,arguments)};e.dynCall_iiiiid=function(){return e.asm.ra.apply(null,arguments)};
e.dynCall_iiiiii=function(){return e.asm.sa.apply(null,arguments)};e.dynCall_iiiiiid=function(){return e.asm.ta.apply(null,arguments)};e.dynCall_iiiiiii=function(){return e.asm.ua.apply(null,arguments)};e.dynCall_iiiiiiii=function(){return e.asm.va.apply(null,arguments)};e.dynCall_iiiiiiiii=function(){return e.asm.wa.apply(null,arguments)};e.dynCall_v=function(){return e.asm.xa.apply(null,arguments)};e.dynCall_vi=function(){return e.asm.ya.apply(null,arguments)};
e.dynCall_vii=function(){return e.asm.za.apply(null,arguments)};e.dynCall_viif=function(){return e.asm.Aa.apply(null,arguments)};e.dynCall_viii=function(){return e.asm.Ba.apply(null,arguments)};e.dynCall_viiii=function(){return e.asm.Ca.apply(null,arguments)};e.dynCall_viiiii=function(){return e.asm.Da.apply(null,arguments)};e.dynCall_viiiiii=function(){return e.asm.Ea.apply(null,arguments)};e.asm=kc;
e.cwrap=function(a,b,c,d){c=c||[];var f=c.every(function(a){return"number"===a});return"string"!==b&&f&&!d?ma(a):function(){var d=c,f=arguments,k=ma(a),n=[],l=0;if(f)for(var m=0;m<f.length;m++){var r=sa[d[m]];r?(0===l&&(l=na()),n[m]=r(f[m])):n[m]=f[m]}d=k.apply(null,n);d="string"===b?ta(d):"boolean"===b?!!d:d;0!==l&&oa(l);return d}};e.UTF8ToString=ua;e.then=function(a){if(e.calledRun)a(e);else{var b=e.onRuntimeInitialized;e.onRuntimeInitialized=function(){b&&b();a(e)}}return e};
Ua=function lc(){e.calledRun||mc();e.calledRun||(Ua=lc)};
function mc(){function a(){if(!e.calledRun&&(e.calledRun=!0,!la)){Ra||(Ra=!0,Ma(Oa));Ma(Pa);if(e.onRuntimeInitialized)e.onRuntimeInitialized();if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;){var a=e.postRun.shift();Qa.unshift(a)}Ma(Qa)}}if(!(0<D)){if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)Sa();Ma(Na);0<D||e.calledRun||(e.setStatus?(e.setStatus("Running..."),setTimeout(function(){setTimeout(function(){e.setStatus("")},
1);a()},1)):a())}}e.run=mc;function u(a){if(e.onAbort)e.onAbort(a);void 0!==a?(ia(a),v(a),a=JSON.stringify(a)):a="";la=!0;throw"abort("+a+"). Build with -s ASSERTIONS=1 for more info.";}e.abort=u;if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.pop()();e.noExitRuntime=!0;mc();


  return Module;
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
    module.exports = Module;
  else if (typeof define === 'function' && define['amd'])
    define([], function() { return Module; });
  else if (typeof exports === 'object')
    exports["Module"] = Module;
  